### ISSUE TITLE
npm install 报错呢

### ISSUE THREAD

**Issue by aprildove** [billyhoomm/XBlog#3]
$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated isparta-loader@2.0.0: Package is deprecated, use https://github.com/deepsweet/istanbul-instrumenter-loader

**Comment by billyhoomm** [comment]
The version of the npm package has not been updated for a long time，Some package versions may need to be updated
